### ISSUE TITLE
Not  working on Unity 2021.3.3f1

### ISSUE THREAD

**Issue by bitfreaks** [greggman/unity-webgl-copy-and-paste#9]
Hi Gregg, just wanted to drop a notice that plugin stops working on the latest Unity version.

**Comment by Draco18s** [comment]
@bitfreaks is this the error you get?

Assets/WebGLCopyAndPaste/Scripts/WebGLCopyAndPaste.cs(35,2): error CS1032: Cannot define/undefine preprocessor symbols after first token in file

If so, all you need to do is move that line above the three `using` lines.

**Comment by 2TheMooon** [comment]
error CS1025: Single-line comment or end-of-line expected
in this case
